export interface Country {
  code: string;
  name: string;
  currencyCode: string;
  currencyName: string;
  currencySymbol: string;
}

export const countries: Country[] = [
  { code: "US", name: "United States", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "CA", name: "Canada", currencyCode: "CAD", currencyName: "Canadian Dollar", currencySymbol: "$" },
  { code: "GB", name: "United Kingdom", currencyCode: "GBP", currencyName: "Pound Sterling", currencySymbol: "£" },
  { code: "AU", name: "Australia", currencyCode: "AUD", currencyName: "Australian Dollar", currencySymbol: "A$" },
  { code: "DE", name: "Germany", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "FR", name: "France", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "JP", name: "Japan", currencyCode: "JPY", currencyName: "Yen", currencySymbol: "¥" },
  { code: "IN", name: "India", currencyCode: "INR", currencyName: "Indian Rupee", currencySymbol: "₹" },
  { code: "BR", name: "Brazil", currencyCode: "BRL", currencyName: "Brazilian Real", currencySymbol: "R$" },
  { code: "CN", name: "China", currencyCode: "CNY", currencyName: "Yuan Renminbi", currencySymbol: "¥" },
  // Add more countries as needed or use a comprehensive list
  { code: "AF", name: "Afghanistan", currencyCode: "AFN", currencyName: "Afghan Afghani", currencySymbol: "؋" },
  { code: "AX", name: "Åland Islands", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "AL", name: "Albania", currencyCode: "ALL", currencyName: "Albanian Lek", currencySymbol: "Lek" },
  { code: "DZ", name: "Algeria", currencyCode: "DZD", currencyName: "Algerian Dinar", currencySymbol: "د.ج" },
  { code: "AS", name: "American Samoa", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "AD", name: "Andorra", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "AO", name: "Angola", currencyCode: "AOA", currencyName: "Angolan Kwanza", currencySymbol: "Kz" },
  { code: "AI", name: "Anguilla", currencyCode: "XCD", currencyName: "East Caribbean Dollar", currencySymbol: "$" },
  { code: "AQ", name: "Antarctica", currencyCode: "XCD", currencyName: "East Caribbean Dollar", currencySymbol: "$" },
  { code: "AG", name: "Antigua and Barbuda", currencyCode: "XCD", currencyName: "East Caribbean Dollar", currencySymbol: "$" },
  { code: "AR", name: "Argentina", currencyCode: "ARS", currencyName: "Argentine Peso", currencySymbol: "$" },
  { code: "AM", name: "Armenia", currencyCode: "AMD", currencyName: "Armenian Dram", currencySymbol: "֏" },
  { code: "AW", name: "Aruba", currencyCode: "AWG", currencyName: "Aruban Florin", currencySymbol: "ƒ" },
  { code: "AT", name: "Austria", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "AZ", name: "Azerbaijan", currencyCode: "AZN", currencyName: "Azerbaijani Manat", currencySymbol: "₼" },
  { code: "BS", name: "Bahamas", currencyCode: "BSD", currencyName: "Bahamian Dollar", currencySymbol: "$" },
  { code: "BH", name: "Bahrain", currencyCode: "BHD", currencyName: "Bahraini Dinar", currencySymbol: ".د.ب" },
  { code: "BD", name: "Bangladesh", currencyCode: "BDT", currencyName: "Bangladeshi Taka", currencySymbol: "৳" },
  { code: "BB", name: "Barbados", currencyCode: "BBD", currencyName: "Barbadian Dollar", currencySymbol: "$" },
  { code: "BY", name: "Belarus", currencyCode: "BYN", currencyName: "Belarusian Ruble", currencySymbol: "Br" },
  { code: "BE", name: "Belgium", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "BZ", name: "Belize", currencyCode: "BZD", currencyName: "Belize Dollar", currencySymbol: "$" },
  { code: "BJ", name: "Benin", currencyCode: "XOF", currencyName: "West African CFA Franc", currencySymbol: "CFA" },
  { code: "BM", name: "Bermuda", currencyCode: "BMD", currencyName: "Bermudian Dollar", currencySymbol: "$" },
  { code: "BT", name: "Bhutan", currencyCode: "BTN", currencyName: "Bhutanese Ngultrum", currencySymbol: "Nu" },
  { code: "BO", name: "Bolivia", currencyCode: "BOB", currencyName: "Bolivian Boliviano", currencySymbol: "$b" },
  { code: "BA", name: "Bosnia and Herzegovina", currencyCode: "BAM", currencyName: "Bosnia-Herzegovina Convertible Mark", currencySymbol: "KM" },
  { code: "BW", name: "Botswana", currencyCode: "BWP", currencyName: "Botswana Pula", currencySymbol: "P" },
  { code: "BV", name: "Bouvet Island", currencyCode: "NOK", currencyName: "Norwegian Krone", currencySymbol: "kr" },
  { code: "IO", name: "British Indian Ocean Territory", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "BN", name: "Brunei Darussalam", currencyCode: "BND", currencyName: "Brunei Dollar", currencySymbol: "$" },
  { code: "BG", name: "Bulgaria", currencyCode: "BGN", currencyName: "Bulgarian Lev", currencySymbol: "лв" },
  { code: "BF", name: "Burkina Faso", currencyCode: "XOF", currencyName: "West African CFA Franc", currencySymbol: "CFA" },
  { code: "BI", name: "Burundi", currencyCode: "BIF", currencyName: "Burundian Franc", currencySymbol: "Fr" },
  { code: "KH", name: "Cambodia", currencyCode: "KHR", currencyName: "Cambodian Riel", currencySymbol: "៛" },
  { code: "CM", name: "Cameroon", currencyCode: "XAF", currencyName: "Central African CFA Franc", currencySymbol: "FCFA" },
  { code: "CV", name: "Cape Verde", currencyCode: "CVE", currencyName: "Cape Verdean Escudo", currencySymbol: "$" },
  { code: "KY", name: "Cayman Islands", currencyCode: "KYD", currencyName: "Cayman Islands Dollar", currencySymbol: "$" },
  { code: "CF", name: "Central African Republic", currencyCode: "XAF", currencyName: "Central African CFA Franc", currencySymbol: "FCFA" },
  { code: "TD", name: "Chad", currencyCode: "XAF", currencyName: "Central African CFA Franc", currencySymbol: "FCFA" },
  { code: "CL", name: "Chile", currencyCode: "CLP", currencyName: "Chilean Peso", currencySymbol: "$" },
  { code: "CX", name: "Christmas Island", currencyCode: "AUD", currencyName: "Australian Dollar", currencySymbol: "A$" },
  { code: "CC", name: "Cocos (Keeling) Islands", currencyCode: "AUD", currencyName: "Australian Dollar", currencySymbol: "A$" },
  { code: "CO", name: "Colombia", currencyCode: "COP", currencyName: "Colombian Peso", currencySymbol: "$" },
  { code: "KM", name: "Comoros", currencyCode: "KMF", currencyName: "Comorian Franc", currencySymbol: "Fr" },
  { code: "CG", name: "Congo", currencyCode: "XAF", currencyName: "Central African CFA Franc", currencySymbol: "FCFA" },
  { code: "CD", name: "Congo, The Democratic Republic of the", currencyCode: "CDF", currencyName: "Congolese Franc", currencySymbol: "Fr" },
  { code: "CK", name: "Cook Islands", currencyCode: "NZD", currencyName: "New Zealand Dollar", currencySymbol: "$" },
  { code: "CR", name: "Costa Rica", currencyCode: "CRC", currencyName: "Costa Rican Colón", currencySymbol: "₡" },
  { code: "CI", name: "Cote D'Ivoire", currencyCode: "XOF", currencyName: "West African CFA Franc", currencySymbol: "CFA" },
  { code: "HR", name: "Croatia", currencyCode: "HRK", currencyName: "Croatian Kuna", currencySymbol: "kn" },
  { code: "CU", name: "Cuba", currencyCode: "CUP", currencyName: "Cuban Peso", currencySymbol: "$" },
  { code: "CY", name: "Cyprus", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "CZ", name: "Czech Republic", currencyCode: "CZK", currencyName: "Czech Koruna", currencySymbol: "Kč" },
  { code: "DK", name: "Denmark", currencyCode: "DKK", currencyName: "Danish Krone", currencySymbol: "kr" },
  { code: "DJ", name: "Djibouti", currencyCode: "DJF", currencyName: "Djiboutian Franc", currencySymbol: "Fr" },
  { code: "DM", name: "Dominica", currencyCode: "XCD", currencyName: "East Caribbean Dollar", currencySymbol: "$" },
  { code: "DO", name: "Dominican Republic", currencyCode: "DOP", currencyName: "Dominican Peso", currencySymbol: "$" },
  { code: "EC", name: "Ecuador", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "EG", name: "Egypt", currencyCode: "EGP", currencyName: "Egyptian Pound", currencySymbol: "£" },
  { code: "SV", name: "El Salvador", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "GQ", name: "Equatorial Guinea", currencyCode: "XAF", currencyName: "Central African CFA Franc", currencySymbol: "FCFA" },
  { code: "ER", name: "Eritrea", currencyCode: "ERN", currencyName: "Eritrean Nakfa", currencySymbol: "Nfk" },
  { code: "EE", name: "Estonia", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "ET", name: "Ethiopia", currencyCode: "ETB", currencyName: "Ethiopian Birr", currencySymbol: "Br" },
  { code: "FK", name: "Falkland Islands (Malvinas)", currencyCode: "FKP", currencyName: "Falkland Islands Pound", currencySymbol: "£" },
  { code: "FO", name: "Faroe Islands", currencyCode: "DKK", currencyName: "Danish Krone", currencySymbol: "kr" },
  { code: "FJ", name: "Fiji", currencyCode: "FJD", currencyName: "Fijian Dollar", currencySymbol: "$" },
  { code: "FI", name: "Finland", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "GF", name: "French Guiana", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "PF", name: "French Polynesia", currencyCode: "XPF", currencyName: "CFP Franc", currencySymbol: "Fr" },
  { code: "TF", name: "French Southern Territories", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "GA", name: "Gabon", currencyCode: "XAF", currencyName: "Central African CFA Franc", currencySymbol: "FCFA" },
  { code: "GM", name: "Gambia", currencyCode: "GMD", currencyName: "Gambian Dalasi", currencySymbol: "D" },
  { code: "GE", name: "Georgia", currencyCode: "GEL", currencyName: "Georgian Lari", currencySymbol: "ლ" },
  { code: "GH", name: "Ghana", currencyCode: "GHS", currencyName: "Ghanaian Cedi", currencySymbol: "₵" },
  { code: "GI", name: "Gibraltar", currencyCode: "GBP", currencyName: "British Pound", currencySymbol: "£" },
  { code: "GR", name: "Greece", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "GL", name: "Greenland", currencyCode: "DKK", currencyName: "Danish Krone", currencySymbol: "kr" },
  { code: "GD", name: "Grenada", currencyCode: "XCD", currencyName: "East Caribbean Dollar", currencySymbol: "$" },
  { code: "GP", name: "Guadeloupe", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "GU", name: "Guam", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "GT", name: "Guatemala", currencyCode: "GTQ", currencyName: "Guatemalan Quetzal", currencySymbol: "Q" },
  { code: "GG", name: "Guernsey", currencyCode: "GBP", currencyName: "British Pound", currencySymbol: "£" },
  { code: "GN", name: "Guinea", currencyCode: "GNF", currencyName: "Guinean Franc", currencySymbol: "Fr" },
  { code: "GW", name: "Guinea-Bissau", currencyCode: "XOF", currencyName: "West African CFA Franc", currencySymbol: "CFA" },
  { code: "GY", name: "Guyana", currencyCode: "GYD", currencyName: "Guyanese Dollar", currencySymbol: "$" },
  { code: "HT", name: "Haiti", currencyCode: "HTG", currencyName: "Haitian Gourde", currencySymbol: "G" },
  { code: "HM", name: "Heard Island and Mcdonald Islands", currencyCode: "AUD", currencyName: "Australian Dollar", currencySymbol: "A$" },
  { code: "VA", name: "Holy See (Vatican City State)", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "HN", name: "Honduras", currencyCode: "HNL", currencyName: "Honduran Lempira", currencySymbol: "L" },
  { code: "HK", name: "Hong Kong", currencyCode: "HKD", currencyName: "Hong Kong Dollar", currencySymbol: "$" },
  { code: "HU", name: "Hungary", currencyCode: "HUF", currencyName: "Hungarian Forint", currencySymbol: "Ft" },
  { code: "IS", name: "Iceland", currencyCode: "ISK", currencyName: "Icelandic Króna", currencySymbol: "kr" },
  { code: "ID", name: "Indonesia", currencyCode: "IDR", currencyName: "Indonesian Rupiah", currencySymbol: "Rp" },
  { code: "IR", name: "Iran, Islamic Republic Of", currencyCode: "IRR", currencyName: "Iranian Rial", currencySymbol: "﷼" },
  { code: "IQ", name: "Iraq", currencyCode: "IQD", currencyName: "Iraqi Dinar", currencySymbol: "د.ع" },
  { code: "IE", name: "Ireland", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "IM", name: "Isle of Man", currencyCode: "GBP", currencyName: "British Pound", currencySymbol: "£" },
  { code: "IL", name: "Israel", currencyCode: "ILS", currencyName: "Israeli New Shekel", currencySymbol: "₪" },
  { code: "IT", name: "Italy", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "JM", name: "Jamaica", currencyCode: "JMD", currencyName: "Jamaican Dollar", currencySymbol: "$" },
  { code: "JE", name: "Jersey", currencyCode: "GBP", currencyName: "British Pound", currencySymbol: "£" },
  { code: "JO", name: "Jordan", currencyCode: "JOD", currencyName: "Jordanian Dinar", currencySymbol: "د.أ" },
  { code: "KZ", name: "Kazakhstan", currencyCode: "KZT", currencyName: "Kazakhstani Tenge", currencySymbol: "₸" },
  { code: "KE", name: "Kenya", currencyCode: "KES", currencyName: "Kenyan Shilling", currencySymbol: "Sh" },
  { code: "KI", name: "Kiribati", currencyCode: "AUD", currencyName: "Australian Dollar", currencySymbol: "A$" },
  { code: "KP", name: "Korea, Democratic People's Republic of", currencyCode: "KPW", currencyName: "North Korean Won", currencySymbol: "₩" },
  { code: "KR", name: "Korea, Republic of", currencyCode: "KRW", currencyName: "Won", currencySymbol: "₩" },
  { code: "KW", name: "Kuwait", currencyCode: "KWD", currencyName: "Kuwaiti Dinar", currencySymbol: "د.ك" },
  { code: "KG", name: "Kyrgyzstan", currencyCode: "KGS", currencyName: "Kyrgyzstani Som", currencySymbol: "с" },
  { code: "LA", name: "Lao People's Democratic Republic", currencyCode: "LAK", currencyName: "Lao Kip", currencySymbol: "₭" },
  { code: "LV", name: "Latvia", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "LB", name: "Lebanon", currencyCode: "LBP", currencyName: "Lebanese Pound", currencySymbol: "ل.ل" },
  { code: "LS", name: "Lesotho", currencyCode: "LSL", currencyName: "Lesotho Loti", currencySymbol: "L" },
  { code: "LR", name: "Liberia", currencyCode: "LRD", currencyName: "Liberian Dollar", currencySymbol: "$" },
  { code: "LY", name: "Libyan Arab Jamahiriya", currencyCode: "LYD", currencyName: "Libyan Dinar", currencySymbol: "ل.د" },
  { code: "LI", name: "Liechtenstein", currencyCode: "CHF", currencyName: "Swiss Franc", currencySymbol: "Fr" },
  { code: "LT", name: "Lithuania", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "LU", name: "Luxembourg", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "MO", name: "Macao", currencyCode: "MOP", currencyName: "Macanese Pataca", currencySymbol: "MOP$" },
  { code: "MK", name: "Macedonia, The Former Yugoslav Republic of", currencyCode: "MKD", currencyName: "Macedonian Denar", currencySymbol: "ден" },
  { code: "MG", name: "Madagascar", currencyCode: "MGA", currencyName: "Malagasy Ariary", currencySymbol: "Ar" },
  { code: "MW", name: "Malawi", currencyCode: "MWK", currencyName: "Malawian Kwacha", currencySymbol: "MK" },
  { code: "MY", name: "Malaysia", currencyCode: "MYR", currencyName: "Malaysian Ringgit", currencySymbol: "RM" },
  { code: "MV", name: "Maldives", currencyCode: "MVR", currencyName: "Maldivian Rufiyaa", currencySymbol: "ރ" },
  { code: "ML", name: "Mali", currencyCode: "XOF", currencyName: "West African CFA Franc", currencySymbol: "CFA" },
  { code: "MT", name: "Malta", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "MH", name: "Marshall Islands", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "MQ", name: "Martinique", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "MR", name: "Mauritania", currencyCode: "MRO", currencyName: "Mauritanian Ouguiya", currencySymbol: "UM" },
  { code: "MU", name: "Mauritius", currencyCode: "MUR", currencyName: "Mauritian Rupee", currencySymbol: "₨" },
  { code: "YT", name: "Mayotte", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "MX", name: "Mexico", currencyCode: "MXN", currencyName: "Mexican Peso", currencySymbol: "$" },
  { code: "FM", name: "Micronesia, Federated States of", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "MD", name: "Moldova, Republic of", currencyCode: "MDL", currencyName: "Moldovan Leu", currencySymbol: "L" },
  { code: "MC", name: "Monaco", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "MN", name: "Mongolia", currencyCode: "MNT", currencyName: "Mongolian Tugrik", currencySymbol: "₮" },
  { code: "MS", name: "Montserrat", currencyCode: "XCD", currencyName: "East Caribbean Dollar", currencySymbol: "$" },
  { code: "MA", name: "Morocco", currencyCode: "MAD", currencyName: "Moroccan Dirham", currencySymbol: "د.م" },
  { code: "MZ", name: "Mozambique", currencyCode: "MZN", currencyName: "Mozambican Metical", currencySymbol: "MT" },
  { code: "MM", name: "Myanmar", currencyCode: "MMK", currencyName: "Myanmar Kyat", currencySymbol: "K" },
  { code: "NA", name: "Namibia", currencyCode: "NAD", currencyName: "Namibian Dollar", currencySymbol: "$" },
  { code: "NR", name: "Nauru", currencyCode: "AUD", currencyName: "Australian Dollar", currencySymbol: "A$" },
  { code: "NP", name: "Nepal", currencyCode: "NPR", currencyName: "Nepalese Rupee", currencySymbol: "₨" },
  { code: "NL", name: "Netherlands", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "AN", name: "Netherlands Antilles", currencyCode: "ANG", currencyName: "Netherlands Antillean Guilder", currencySymbol: "ƒ" },
  { code: "NC", name: "New Caledonia", currencyCode: "XPF", currencyName: "CFP Franc", currencySymbol: "Fr" },
  { code: "NZ", name: "New Zealand", currencyCode: "NZD", currencyName: "New Zealand Dollar", currencySymbol: "$" },
  { code: "NI", name: "Nicaragua", currencyCode: "NIO", currencyName: "Nicaraguan Córdoba", currencySymbol: "$C" },
  { code: "NE", name: "Niger", currencyCode: "XOF", currencyName: "West African CFA Franc", currencySymbol: "CFA" },
  { code: "NG", name: "Nigeria", currencyCode: "NGN", currencyName: "Naira", currencySymbol: "₦" },
  { code: "NU", name: "Niue", currencyCode: "NZD", currencyName: "New Zealand Dollar", currencySymbol: "$" },
  { code: "NF", name: "Norfolk Island", currencyCode: "AUD", currencyName: "Australian Dollar", currencySymbol: "A$" },
  { code: "MP", name: "Northern Mariana Islands", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "NO", name: "Norway", currencyCode: "NOK", currencyName: "Norwegian Krone", currencySymbol: "kr" },
  { code: "OM", name: "Oman", currencyCode: "OMR", currencyName: "Omani Rial", currencySymbol: "ر.ع" },
  { code: "PK", name: "Pakistan", currencyCode: "PKR", currencyName: "Pakistani Rupee", currencySymbol: "₨" },
  { code: "PW", name: "Palau", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "PS", name: "Palestinian Territory, Occupied", currencyCode: "ILS", currencyName: "Israeli New Shekel", currencySymbol: "₪" },
  { code: "PA", name: "Panama", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "PG", name: "Papua New Guinea", currencyCode: "PGK", currencyName: "Papua New Guinean Kina", currencySymbol: "K" },
  { code: "PY", name: "Paraguay", currencyCode: "PYG", currencyName: "Paraguayan Guarani", currencySymbol: "₲" },
  { code: "PE", name: "Peru", currencyCode: "PEN", currencyName: "Peruvian Sol", currencySymbol: "S/" },
  { code: "PH", name: "Philippines", currencyCode: "PHP", currencyName: "Philippine Peso", currencySymbol: "₱" },
  { code: "PN", name: "Pitcairn", currencyCode: "GBP", currencyName: "British Pound", currencySymbol: "£" },
  { code: "PL", name: "Poland", currencyCode: "PLN", currencyName: "Polish Zloty", currencySymbol: "zł" },
  { code: "PT", name: "Portugal", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "PR", name: "Puerto Rico", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "QA", name: "Qatar", currencyCode: "QAR", currencyName: "Qatari Rial", currencySymbol: "ر.ق" },
  { code: "RE", name: "Reunion", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "RO", name: "Romania", currencyCode: "RON", currencyName: "Romanian Leu", currencySymbol: "lei" },
  { code: "RU", name: "Russian Federation", currencyCode: "RUB", currencyName: "Russian Ruble", currencySymbol: "₽" },
  { code: "RW", name: "Rwanda", currencyCode: "RWF", currencyName: "Rwandan Franc", currencySymbol: "Fr" },
  { code: "SH", name: "Saint Helena", currencyCode: "GBP", currencyName: "British Pound", currencySymbol: "£" },
  { code: "KN", name: "Saint Kitts and Nevis", currencyCode: "XCD", currencyName: "East Caribbean Dollar", currencySymbol: "$" },
  { code: "LC", name: "Saint Lucia", currencyCode: "XCD", currencyName: "East Caribbean Dollar", currencySymbol: "$" },
  { code: "PM", name: "Saint Pierre and Miquelon", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currencyCode: "XCD", currencyName: "East Caribbean Dollar", currencySymbol: "$" },
  { code: "WS", name: "Samoa", currencyCode: "WST", currencyName: "Samoan Tala", currencySymbol: "T" },
  { code: "SM", name: "San Marino", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "ST", name: "Sao Tome and Principe", currencyCode: "STD", currencyName: "São Tomé and Príncipe Dobra", currencySymbol: "Db" },
  { code: "SA", name: "Saudi Arabia", currencyCode: "SAR", currencyName: "Saudi Riyal", currencySymbol: "ر.س" },
  { code: "SN", name: "Senegal", currencyCode: "XOF", currencyName: "West African CFA Franc", currencySymbol: "CFA" },
  { code: "CS", name: "Serbia and Montenegro", currencyCode: "YUM", currencyName: "Yugoslavian Dinar", currencySymbol: "د.ص" },
  { code: "SC", name: "Seychelles", currencyCode: "SCR", currencyName: "Seychellois Rupee", currencySymbol: "₨" },
  { code: "SL", name: "Sierra Leone", currencyCode: "SLL", currencyName: "Sierra Leonean Leone", currencySymbol: "Le" },
  { code: "SG", name: "Singapore", currencyCode: "SGD", currencyName: "Singapore Dollar", currencySymbol: "$" },
  { code: "SK", name: "Slovakia", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "SI", name: "Slovenia", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "SB", name: "Solomon Islands", currencyCode: "SBD", currencyName: "Solomon Islands Dollar", currencySymbol: "$" },
  { code: "SO", name: "Somalia", currencyCode: "SOS", currencyName: "Somali Shilling", currencySymbol: "Sh" },
  { code: "ZA", name: "South Africa", currencyCode: "ZAR", currencyName: "South African Rand", currencySymbol: "R" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", currencyCode: "GBP", currencyName: "British Pound", currencySymbol: "£" },
  { code: "ES", name: "Spain", currencyCode: "EUR", currencyName: "Euro", currencySymbol: "€" },
  { code: "LK", name: "Sri Lanka", currencyCode: "LKR", currencyName: "Sri Lankan Rupee", currencySymbol: "₨" },
  { code: "SD", name: "Sudan", currencyCode: "SDG", currencyName: "Sudanese Pound", currencySymbol: "ج.س" },
  { code: "SR", name: "Suriname", currencyCode: "SRD", currencyName: "Surinamese Dollar", currencySymbol: "$" },
  { code: "SJ", name: "Svalbard and Jan Mayen", currencyCode: "NOK", currencyName: "Norwegian Krone", currencySymbol: "kr" },
  { code: "SZ", name: "Swaziland", currencyCode: "SZL", currencyName: "Swazi Lilangeni", currencySymbol: "L" },
  { code: "SE", name: "Sweden", currencyCode: "SEK", currencyName: "Swedish Krona", currencySymbol: "kr" },
  { code: "CH", name: "Switzerland", currencyCode: "CHF", currencyName: "Swiss Franc", currencySymbol: "Fr" },
  { code: "SY", name: "Syrian Arab Republic", currencyCode: "SYP", currencyName: "Syrian Pound", currencySymbol: "ل.س" },
  { code: "TW", name: "Taiwan, Province of China", currencyCode: "TWD", currencyName: "New Taiwan Dollar", currencySymbol: "$" },
  { code: "TJ", name: "Tajikistan", currencyCode: "TJS", currencyName: "Tajikistani Somoni", currencySymbol: "ЅМ" },
  { code: "TZ", name: "Tanzania, United Republic of", currencyCode: "TZS", currencyName: "Tanzanian Shilling", currencySymbol: "TSh" },
  { code: "TH", name: "Thailand", currencyCode: "THB", currencyName: "Thai Baht", currencySymbol: "฿" },
  { code: "TL", name: "Timor-Leste", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "TG", name: "Togo", currencyCode: "XOF", currencyName: "West African CFA Franc", currencySymbol: "CFA" },
  { code: "TK", name: "Tokelau", currencyCode: "NZD", currencyName: "New Zealand Dollar", currencySymbol: "$" },
  { code: "TO", name: "Tonga", currencyCode: "TOP", currencyName: "Tongan Pa'anga", currencySymbol: "T$" },
  { code: "TT", name: "Trinidad and Tobago", currencyCode: "TTD", currencyName: "Trinidad and Tobago Dollar", currencySymbol: "$" },
  { code: "TN", name: "Tunisia", currencyCode: "TND", currencyName: "Tunisian Dinar", currencySymbol: "د.ت" },
  { code: "TR", name: "Turkey", currencyCode: "TRY", currencyName: "Turkish Lira", currencySymbol: "₺" },
  { code: "TM", name: "Turkmenistan", currencyCode: "TMT", currencyName: "Turkmenistan Manat", currencySymbol: "m" },
  { code: "TC", name: "Turks and Caicos Islands", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "TV", name: "Tuvalu", currencyCode: "AUD", currencyName: "Australian Dollar", currencySymbol: "A$" },
  { code: "UG", name: "Uganda", currencyCode: "UGX", currencyName: "Ugandan Shilling", currencySymbol: "USh" },
  { code: "UA", name: "Ukraine", currencyCode: "UAH", currencyName: "Ukrainian Hryvnia", currencySymbol: "₴" },
  { code: "AE", name: "United Arab Emirates", currencyCode: "AED", currencyName: "UAE Dirham", currencySymbol: "د.إ" },
  { code: "UM", name: "United States Minor Outlying Islands", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "UY", name: "Uruguay", currencyCode: "UYU", currencyName: "Uruguayan Peso", currencySymbol: "$" },
  { code: "UZ", name: "Uzbekistan", currencyCode: "UZS", currencyName: "Uzbekistani Som", currencySymbol: "лв" },
  { code: "VU", name: "Vanuatu", currencyCode: "VUV", currencyName: "Vanuatu Vatu", currencySymbol: "Vt" },
  { code: "VE", name: "Venezuela", currencyCode: "VEF", currencyName: "Venezuelan Bolívar", currencySymbol: "Bs" },
  { code: "VN", name: "Viet Nam", currencyCode: "VND", currencyName: "Vietnamese Dong", currencySymbol: "₫" },
  { code: "VG", name: "Virgin Islands, British", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "VI", name: "Virgin Islands, U.S.", currencyCode: "USD", currencyName: "US Dollar", currencySymbol: "$" },
  { code: "WF", name: "Wallis and Futuna", currencyCode: "XPF", currencyName: "CFP Franc", currencySymbol: "Fr" },
  { code: "EH", name: "Western Sahara", currencyCode: "MAD", currencyName: "Moroccan Dirham", currencySymbol: "د.م" },
  { code: "YE", name: "Yemen", currencyCode: "YER", currencyName: "Yemeni Rial", currencySymbol: "ر.ي" },
  { code: "ZM", name: "Zambia", currencyCode: "ZMW", currencyName: "Zambian Kwacha", currencySymbol: "ZK" },
  { code: "ZW", name: "Zimbabwe", currencyCode: "ZWL", currencyName: "Zimbabwean Dollar", currencySymbol: "$" }
];
